// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoyG-FwqSD9qxtyAtMAs9AYkVmr7LFouw',
    appId: '1:908468746180:web:8948e2b8c385ed300a5691',
    messagingSenderId: '908468746180',
    projectId: 'rock-scanner-97922',
    authDomain: 'rock-scanner-97922.firebaseapp.com',
    storageBucket: 'rock-scanner-97922.firebasestorage.app',
    measurementId: 'G-5QVL59HBD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXMrL9UrpUNcNw8o3XtPtU6w5Yds9IDjY',
    appId: '1:908468746180:android:137f807ea1c37ccc0a5691',
    messagingSenderId: '908468746180',
    projectId: 'rock-scanner-97922',
    storageBucket: 'rock-scanner-97922.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0nXOWoUi6heBVF07m7a3G2OY0svARsfI',
    appId: '1:908468746180:ios:0eacf7aa69dc27720a5691',
    messagingSenderId: '908468746180',
    projectId: 'rock-scanner-97922',
    storageBucket: 'rock-scanner-97922.firebasestorage.app',
    iosBundleId: 'com.example.rockScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0nXOWoUi6heBVF07m7a3G2OY0svARsfI',
    appId: '1:908468746180:ios:0eacf7aa69dc27720a5691',
    messagingSenderId: '908468746180',
    projectId: 'rock-scanner-97922',
    storageBucket: 'rock-scanner-97922.firebasestorage.app',
    iosBundleId: 'com.example.rockScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoyG-FwqSD9qxtyAtMAs9AYkVmr7LFouw',
    appId: '1:908468746180:web:9fbf390d60fa73660a5691',
    messagingSenderId: '908468746180',
    projectId: 'rock-scanner-97922',
    authDomain: 'rock-scanner-97922.firebaseapp.com',
    storageBucket: 'rock-scanner-97922.firebasestorage.app',
    measurementId: 'G-LRMPQ9F22H',
  );
}
